export const MAX_TOTAL_JOB_TIME = 8 * 60 * 1000;
export const MAX_STAGE_TIME = 60 * 1000;
export const MAX_WEB_SEARCHES = 8;
export const MAX_PAGES_READ = 12;
export const MAX_TECHNICAL_PAGES = 5;
export const MAX_SOURCE_COUNT = 20;
export const MIN_SOURCE_COUNT_TO_PUBLISH = 3;
export const MAX_RETRIES_PER_STAGE = 1;
export const MAX_ACTIVE_USER_JOBS = 2;
export const MAX_GLOBAL_CONCURRENT_JOBS = 4;
export const DOSSIER_CAN_FINALIZE_AFTER_ARTICLE = true;

export const researchJobLimits = {
  MAX_TOTAL_JOB_TIME,
  MAX_STAGE_TIME,
  MAX_WEB_SEARCHES,
  MAX_PAGES_READ,
  MAX_TECHNICAL_PAGES,
  MAX_SOURCE_COUNT,
  MIN_SOURCE_COUNT_TO_PUBLISH,
  MAX_RETRIES_PER_STAGE,
  MAX_ACTIVE_USER_JOBS,
  MAX_GLOBAL_CONCURRENT_JOBS,
  DOSSIER_CAN_FINALIZE_AFTER_ARTICLE
};
