export {
  DOSSIER_CAN_FINALIZE_AFTER_ARTICLE,
  MAX_ACTIVE_RESEARCH_JOBS,
  MAX_ACTIVE_USER_JOBS,
  MAX_GLOBAL_CONCURRENT_JOBS,
  MAX_PAGES_READ,
  MAX_RETRIES_PER_STAGE,
  MAX_SOURCE_COUNT,
  MAX_STAGE_TIME,
  MAX_TECHNICAL_PAGES,
  MAX_TOTAL_JOB_TIME,
  MAX_WEB_SEARCHES,
  MIN_SOURCE_COUNT_TO_PUBLISH,
  researchJobLimits
} from "@deeptechly/research";
